services:
  - type: web
    name: dynamic-pricing-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: USE_IN_MEMORY_DB
        value: "true"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "*"
